### ISSUE TITLE
Ifc label in COBie Excel output (Component Sheet)

### ISSUE THREAD

**Issue by redgeway-edocs** [xBimTeam/XbimWindowsUI#10]
In COBieLite we have access to the ifc Label /External Identifier for a given component, can this be added to the standard COBie Excel output?

**Comment by andyward** [comment]
Well, all COBie sheets should have a ExtIdentifier column (usually a purple column) which will typically have the IfcGUID of the associated IFC entity originating the row. You *could* alter the mappings to put the Entity label in that field, but I suspect that's not a great plan since Entity Labels are not stable between versions/exports, whereas Guid (mostly) are. A small change to a source model will typically renumber most entities in the IFC

Why do you need this field? If it's to associate the COBie data with the IFC model, I'd consider other approaches (like the Guid). Bear in mind that IFC Label is really an internal STEP implementation detail.

**Comment by redgeway-edocs** [comment]
Yes, we would need this field to associate the COBie data with an IFC model. This is by using the Xbim Web viewer which seems to use an external id to associate the data and this external id appears to be the ifc label id and doesn't appear in the COBie data set.

**Comment by andyward** [comment]
OK, in which case I think this should be in [XbimTeam/XbimWebUI](https://github.com/xBimTeam/XbimWebUI) repo, and then @martin1cerny may be able to offer some advice . Can you [Move it?](https://github-issue-mover.appspot.com/)
