### ISSUE TITLE
How to get IfcProperty quickly

### ISSUE THREAD

**Issue by azura-vergo** [xBimTeam/XbimWindowsUI#11]
hello andy,can i ask you some personal question.
i want to get all the Property from the IFC file group by element of different entity
and i use the follow code
//IfcElement ifc
IfcProperty[] source4 = ifc.PropertySets.SelectMany((IfcPropertySet p) => p.HasProperties).ToArray<IfcProperty>();
but it spend at least 15ms just get one IfcElement Property .
for a 40m ifc file,it need more than 4 mins to get all the property
i want to know is there has some other method to get the property more quickly.

**Comment by CBenghi** [comment]
Hello,
another way to look at the problem is to start from the IfcRelDefinesByProperties class.

You can start from enumerating them with model.Instances.OfyType<IfcRelDefinesByProperties >()...
Then Keep a dictionary of the RelatingPropertyDefinition field and associated properties, probably through it's entity label.
Then attach them to all instances of the RelatedObjects field. 
This way you would avoid the transversal of any duplicates and save you time.
Hope this helps,
Claudio

**Comment by azura-vergo** [comment]
thanks you Claudio,i am doing some test now,thanks your help
