### ISSUE TITLE
Exception in Xbim.Presentation.DrawingControl3D

### ISSUE THREAD

**Issue by andykazmaier** [xBimTeam/XbimWindowsUI#3]
Hey folks,

I get an exception when opening a view that includes an xbim:DrawingControl3D, after installing from the latest WindowsUI package in NuGet.

I've attached a screenshot.  Anyone else seeing this?  If I revert my version of HelixToolkit.Wpf to an earlier version (e.g., 2014.2.410.0), the problem goes away.

Thanks,

Andy Kazmaier
![drawingcontrol3dexceptoin](https://cloud.githubusercontent.com/assets/10751238/6200529/631d56be-b439-11e4-8e49-1ae5a371a71d.png)

**Comment by andykazmaier** [comment]
I'm getting mixed results, so I'm closing this until I can reproduce it properly.

**Comment by mwymwy** [comment]
Sorry for awaking this post, I won't do it without a good reason ... 
I faced a similar problem and when doing a google request with DrawingControl3D and helixToolkit.wpf exception I landed here and didn't found anything to put me on rails.

As I found a way to work around this issue, I thought some other people would be glad to get the tip so I came back here to add my workaround.

First my problem : 
Get XBim.WindowsUI (3.1.12) from Nuget -> it came with last version of HelixToolkit.Wpf dependancies (2015.1.629)
couldn't create a working WPF Control with DrawingControl3D inside because of "Impossible de charger le fichier ou l'assembly 'HelixToolkit.Wpf, Version=2015.1.545.0, Culture=neutral, PublicKeyToken=52aa3500039caf0d'"

I took a look at XBim.WindowsUI.Nuget solution because it had a working WPF XBimXplorer inside and I figured out that it did used HelixToolkit.Wpf with older version (the minimal one expected, as said 2015.1.545)

So here the fix :
Open your Package manager console (Tools>Nuget Packages manager>Console)
uninstall XBim.WindowsUI and everything else that would need HelixToolkit or HelixToolkit.Wpf :
"Uninstall-Package Xbim.WindowsUI"

then uninstall HelixToolkit and .wpf

"Uninstall-Package HelixToolkit.Wpf"
"Uninstall-Package HelixToolkit"

re-install it with proper version :
"Install-Package HelixToolkit.Wpf -Version 2015.1.545"
re-install latest Xbim.WindowsUI
"Install-Package Xbim.WindowsUI"

Maybe this can help ?

**Comment by CBenghi** [comment]
Hello, this was an odd one...
Everything seemed to work fine for me, internally in Xplorer, but then I think nuget was mixing up versions of Helix because there is a .0 version available that was considered fitting the specs when it was not.
I've resolved updating to the latest version of HelixToolkit. I've tested it a bit and it seems stable.
The Xbim.WindowsUI that fixes this is version 3.1.13.
It might take a few minutes before it's available on nuget.
Let me know if this fixes the problem for you without odd workarounds.
Best,
Claudio
