### ISSUE TITLE
Geometry not added to the GeometryDB, causes ShowDoors, ShowWindows, etc., to fail

### ISSUE THREAD

**Issue by andykazmaier** [xBimTeam/XbimWindowsUI#4]
Hello,

I notice that the xbim explorer which is included in the WindowsUI Nuget package no longer includes view options for showing/hiding doors, slabs, windows, etc.  But, the DrawingControl3D still has properties for showing and hiding those Ifc types.

When I toggle those properties,  nothing happens because there are no scenes or layers, and the Hide&lt;T&gt;() method ends up hiding nothing.

Is this something that should be working?  Does the file have to be exported from Revit in a specific way?  Thanks,

Andy Kazmaier

**Comment by andykazmaier** [comment]
Here's the code of which I speak.  I really hope someone wants to help.

        /// <summary>
        ///   Hides all instances of the specified type
        /// </summary>
        public void Hide<T>()
        {
            var ifcType = IfcMetaData.IfcType(typeof(T));
            var toHide = ifcType.Name + ";";
            foreach (var subType in ifcType.NonAbstractSubTypes)
                toHide += subType.Name + ";";
            foreach (var scene in Scenes)
                foreach (var layer in scene.SubLayers) //go over top level layers only
                    if (toHide.Contains(layer.Name + ";"))
                        layer.HideAll();
        }

**Comment by andykazmaier** [comment]
Ultimately, this call fails:

        private XbimGeometryHandleCollection GetGeometryHandlesBySurfaceStyle(XbimGeometryType geomType)
        {
            XbimGeometryHandleCollection result = new XbimGeometryHandleCollection();
            Api.JetSetCurrentIndex(sesid, table, geometryTableStyleIndex);
            Api.MakeKey(sesid, table, (byte)geomType, MakeKeyGrbit.NewKey);
            if (Api.TrySeek(sesid, table, SeekGrbit.SeekGE))
            {
                Api.MakeKey(sesid, table, (byte)geomType, MakeKeyGrbit.NewKey | MakeKeyGrbit.FullColumnEndLimit);
                if (Api.TrySetIndexRange(sesid, table, SetIndexRangeGrbit.RangeUpperLimit | SetIndexRangeGrbit.RangeInclusive))
                {
                    do
                    {
                        int? style = Api.RetrieveColumnAsInt32(sesid, table, _colIdStyleLabel, RetrieveColumnGrbit.RetrieveFromIndex);
                        short? ifcType = Api.RetrieveColumnAsInt16(sesid, table, _colIdProductIfcTypeId, RetrieveColumnGrbit.RetrieveFromIndex);
                        int? product = Api.RetrieveColumnAsInt32(sesid, table, _colIdProductLabel, RetrieveColumnGrbit.RetrieveFromIndex);
                        int? geomId = Api.RetrieveColumnAsInt32(sesid, table, _colIdGeometryLabel, RetrieveColumnGrbit.RetrieveFromIndex);
                        result.Add(new XbimGeometryHandle(geomId.Value, geomType, product.Value, ifcType.Value, style.Value));
                    } while (Api.TryMoveNext(sesid, table));
                }

            }
            return result;
        }

Because the call to Api.TrySetIndexRange fails.  The document for that indicates that it requires a key made by Api.JetMakeKey, but I don't know if that is causing the problem, since the old version works, and relies on Api.MakeKey as well.

**Comment by CBenghi** [comment]
Hi,
there have been a great deal of changes around the way we manage layers in the viewer since last fall.
This is because we have changed the way geometry is stored in the xbim files as well.
My view is that in the medium term plan we should be dropping the old version, but before we can do that I want to ensure we have stable version that is fully capable of dealing with new and old implementation and allow code transitions via the obsolete tags with adequate guidance.

The mechanisms for hiding/showing layers used do be based on layer names, but we have a more configurable mechanism available through the layerstyler interface to allow arbitrary viewing, grouping while retaining optimisation purposes.

The hide/show<t> functions on the component do not reflect these changes yet.
We will have to remove them eventually, but it's still possible for you to achieve the same functions, if you control the layerstyler adequately, have a look at ILayerStyler (it would certainly need better documentation, let me know if I can help you understand it).

There should be no need for you to do anything in the underlying libraries, unless there are bugs identified, but in that case I'd be happy to solve them out.

Best,
Claudio

**Comment by andykazmaier** [comment]
Thanks very much for the response, Claudio.

I did look through ILayerStylerV2 and saw that the only method to implement is BuildScene.  In fact, I reverted to trying to use the older style geometry just because I could not see how the new implementation of that interface was handling layers.

It appears to me that the implementation of ILayerStylerV2, specifically via SurfaceLayerStyler, implements BuildScene, which seems to support a list of exclusions as a parameter.  I can only surmise that the list of exclusions is meant to be types of IfcObjects to hide.

But it seems odd to have to rebuild the scene every time one has to hide or show objects.

Furthermore, any code which deals with the "exclude" parameter is nonexistent, and the code that purports to exclude spaces by default appears to be commented out.

Am I barking up the wrong tree?  :)  I'm looking at SurfaceLayerStyler.cs, which is in Xbim.Presentation.

Thanks for the assist!

Andy

**Comment by KaiFlorian** [comment]
Hi Andy,

I am facing this issue as well. ModelOpacity also does not work. Have you found any solution for this?

Thanks in advance,
Kai

**Comment by andykazmaier** [comment]
Hi Kai,

No solution yet - I'm hoping Claudio will have some time, but I imagine other parts of xBIM are a higher priority right now than the XAML controls.  I did also notice that the opacity broke at the same time the show/hide functionality was dropped with the newer layer management code.

I am more than happy to contribute to the development - so hopefully your interest here will help raise the importance. :)

Andy

**Comment by KaiFlorian** [comment]
Thanks heaps Andy. Looking forward to know the solution for this issue. 
Kai

**Comment by CBenghi** [comment]
Hi guys,
I've just posted an udpate making ExcludedTypes public (in the develop branch still).
You can set it before loading the model to exclude the types you don't want to see.
Let me know if this works for you.

**Comment by KaiFlorian** [comment]
Hi Claudio,

I can see that you have included this in the develop branch. I am trying to compile and build this branch but it is unable to find the required nuget packages. Is there anyway specific way to build the develop branch or I should include the modified parts into the master project.

Thanks,
Kai

**Comment by andyward** [comment]
Kai, make sure you have the Myget sources defined in your Nuget Package Sources. We're using Myget for the develop branches rather than Nuget :

![image](https://cloud.githubusercontent.com/assets/923699/9134804/dbe7ff8c-3cff-11e5-89de-906603039014.png)

If you still have problems, let us know what package you can't get.

**Comment by KaiFlorian** [comment]
Thanks Andy. I can get all the packages through myget.
