### ISSUE TITLE
Issue with loading IFC files in Xbim explorer

### ISSUE THREAD

**Issue by atazadeh** [xBimTeam/XbimWindowsUI#5]
Hi all,
I downloaded the Xbim.WindowsUI project and also loaded its Nuget packages into the project. I can run the XbimXplorer. However, when I want to load an IFC2X3 file, the following error message pops up saying that "could not load the assembly file Xbim.Geometry.Engine32.dll". I also tried to load both  "Xbim.Geometry.Engine32.dll" and "Xbim.Geometry.Engine64.dll" in x86 and x64 folders respectively. But the issue still exists. I am using Visual studio 2012. Can anyone please tell me the correct way for running the WindowsUI project and how should I load those dll files into the project?

![capture1](https://cloud.githubusercontent.com/assets/8553060/7955419/880ffb9c-0a1b-11e5-8c6f-386c14962124.PNG)

Thanks

**Comment by LloydPickering** [comment]
Why did you load in the other Nuget packages as source rather than using the exiting packages? There's not necessarily anything wrong with that approach, but unless you need to make changes to the Nuget packages, it will make your life harder (Don't forget you can still always create your own class extensions if you need to add net new function to existing libraries).

Essentially the problem you have is the Nuget Package for Geometry has an install script in it to copy those dlls (Engine32 and Engine64) into the output folder of your solution. These contain the unmanaged code required to generate geometry from an IFC File (but are only used in geom generation, not reading already processed geometry).

This means they need to be in your output folder (I think in a sub folder of your output folder) in order to convert and Ifc to an Xbim file.

**Comment by atazadeh** [comment]
Thank you for your comment. You mean I can create a windows based
application from scratch and then import xbim nuget libraries into this
project. I tried this but i am not sure how the windows based UI components
such as 3d viewer can be loaded within the project. Can you please explain
what do you mean by other packages as source?

Or alternatively, I put those dlls into subfolders of Output folder in
Xbim.WibdowsUI solution but I still get the same error.

My question is simply if I want to develop a very simple windows based bim
viewer using xbim toolkit, what would be the starting point. Do I need to
use Xbim.windowsUI source code uploaded in Github or I should start from
scratch and import necessary nuget libraries?

Thanks for your help
Benham

**Comment by andykazmaier** [comment]
Try this.

1) Download the WindowsUI Nuget package - https://github.com/xBimTeam/XbimWindowsUI
2) Open the solution file in visual studio.  I'm using 2013.
3) Right-click on the solution, and select "Enable Nuget Package Restore".  Confirm the selection.
4) Right-click on the solution, and select "Manage Nuget Packages for Solution".
5) Notice the warning on the dialog that says "Some NuGet packages are missing..."
6) Click on "Restore".  Close the dialog when it's finished.
7) Right-click on the xbimXplorer and select "Select as startup project".
8) Then hit run, start, whatever you call it.  :)

There are some IFC files that don't work for me, and others that do.  It seemed to be an issue of getting the latest geometry.  You'll notice if you download the WindowsUI package that it relies on the 3.0.10 version of the geometry, which is not the latest.

You can just create your own application from scratch, importing the Presentation package from NuGet.  It makes available the XAML controls that are used in the Xplorer I just referenced.

HTH,

Andy Kazmaier

**Comment by atazadeh** [comment]
Thanks very much Andy. That helped.

Behnam

**Comment by andyward** [comment]
Worth noting that the Enable Nuget Package Restore approach on the solution [is no longer recommended](http://blog.davidebbo.com/2014/01/the-right-way-to-restore-nuget-packages.html) and indeed the option is not in VS2015. Since Nuget 2.7 the restore process is automated - see https://docs.nuget.org/consume/package-restore#package-restore-approaches.

i.e. if you've got the latest VS updates, package restore should work automagically
