### ISSUE TITLE
How to show geometry of electrical equipment?

### ISSUE THREAD

**Issue by TadeuszWilczek** [xBimTeam/XbimWindowsUI#56]
xBim explorer ver 3.2.1.0 does not show electrical equipment (IfcElectricDistributionPoint, IfcFlowSegment, IfcFlowFitting...)
xBim explorer ver 2.4.1.28 and other Ifc viewers shows this elements.
xBim explorer ver 4.0.0.0 fails: 
![ifc fail](https://cloud.githubusercontent.com/assets/20854151/21609793/be84890a-d1c4-11e6-8543-b3e5bf82de30.JPG)

**Comment by theebow** [comment]
Hi,
your ifc file is surely out of work, i never had trouble for showing element from electrical domain in ifc V4.0
try this one (please rename the file with the "ifc" extension, because i could upload only "txt" one)

[Elec253.txt](https://github.com/xBimTeam/XbimWindowsUI/files/685200/Elec253.txt)

**Comment by LloydPickering** [comment]
The error message states that you have a schema problem.

I'd advise you to check what schema your IFC file is, and see if it is what
is expected.

Probably you are somehow generating an invalid file with mixed standards.

**Comment by LloydPickering** [comment]
That makes sense.

IFC 3 (aka 2x3) and IFC 4 are supported but prior versions are pretty rare
and are only supported on a 'best endeavours' approach.

Is there any way you could export the original models in a more modern IFC
format?
