### ISSUE TITLE
Question about language

### ISSUE THREAD

**Issue by GLFichera** [xBimTeam/XbimWindowsUI#70]
Hi! I would change the language of the program. Can i make this?

**Comment by CBenghi** [comment]
We have not yet identified a complete strategy for internationalisation.
If you are committed we can establish a mechanism.

**Comment by GLFichera** [comment]
It's possible change manually every text? Some informations ,like property of an item, don't appear in the file XAML of Visual Studio because they are binded.

**Comment by CBenghi** [comment]
Are you talking about property-sets and their names? In that case that information is hard-coded in the IFC files, it might take a bit of work to inject a translator.

**Comment by GLFichera** [comment]
Yes. I would translate that names from English to Italian

**Comment by CBenghi** [comment]
Let's have a chat on Skype, search for Claudio Benghi or Bonghi and I'll try to help.

**Comment by I-Sokolov** [comment]
Property set names and property names should NOT be translated.
These are IFC keywords. As soon you change it downstream application has no chance to get property.
You may add custom properties with own names but do not expect receiver will interpret values

**Comment by CBenghi** [comment]
@I-Sokolov, I've spoken to @GLFichera he was only interested in providing translation in the UI, the files would of course stay the same.

**Comment by I-Sokolov** [comment]
Are you aware IFC PSD (Property Set Definition) files contains local descriptions for property and sets names?

IMHO it would be reasonable to get from these files. At least this is an official buildingSMART translation.

Actually published only contains only few languages and do not have Italian, but if somebody translate bSI must be happy to update.

PSDs are embedded in documentation and scheme is published here
http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/pset_actionrequest.htm
http://www.buildingsmart-tech.org/downloads/Property%20Sets/psd-for-ifc4?searchterm=PSD

http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/pset_actionrequest.htm

**Comment by I-Sokolov** [comment]
The main idea of PSD files to be metadata for properties, to dynamically describe properties types, ranges etc.
You need it mainly when generate IFC file, because on reading you can guess type from IFC file itself. Possible this is why xbim did not implement it :)

Translation is a new use-case in IFC4.

Now, You can not hardcode or resx property sets because of its dynamic nature. You have to use external source, maybe custom / extendable, so why not to use PSD?

Really, I would prefer property names to be in English even in UI, because they are kind of keywords and translation may obscure users. Local names may be used for commenting or description.
