### ISSUE TITLE
Multiple selection

### ISSUE THREAD

**Issue by GLFichera** [xBimTeam/XbimWindowsUI#87]
How can I select multiple object in drawing control knowing their entity labels? I add these Ifcelements in drawingControl.Selection but doesn't work.

**Comment by GLFichera** [comment]
I resolved it. I had created a new EntitySelection variable and I added Objcets that I wanted select to this variable. Then I had assigned this variable to drawingControl.Selection:

var ent=new EntitySelection();
foreach(var obj in listObj)
    ent.Add(obj);
drawingControl.Selection=ent;

**Comment by YauronBis** [comment]
My bad, i was try this to introduce multiple selection too ! But Setting a new EntitySelection() make bug in Void ReplaceSelection, because newVal is null. May we have to had another constructor to entitySelection to directely give Selection list and avoid this error ?

**Comment by GLFichera** [comment]
ReplaceSelection isn't involved in this section because ReplaceSelection is called when you select an other object on the 3D Viewer.

**Comment by YauronBis** [comment]
I have my own Navigation panel, because this is not native ifc data.
I have every EntityLabel info i need on it : Location data, Distinct Materials Data, Distinct PropertySet Data, Unity data, and Construction data are in a separate TreeList,. Construction Data are regrouped under Typed Element when it exists, and virtual one, when they don't. It make more means for me.
But when i select a specific location, or a Typed Element, i wish i can set a multiple selection in Drawing3dControl with every EntityLabel it means. Actually, Selection work with one object in bi-directional. I wish i can do the same with many EntityLabel now.

How can i do ?
